title: Sam Wilson
description: The personal website of a coder from Fremantle, Western Australia.
url: https://samwilson.id.au
twitter_name: samwilson
embeds:
  flickr: "&^https://www\\.flickr\\.com/.*?(\\d+).*&"
  commons: "|^https://commons.wikimedia.org/wiki/File:(.*)|"
output_exclude:
  - "|/_redirects|"
  - "|/favicon.ico|"
  - "|/favicon-16x16.png|"
  - "|/favicon-32x32.png|"
